baseURL = 'https://liangzhang-keepmoving.github.io/'
languageCode = 'en-us'
title = 'Liang Zhang'
theme = "PaperMod"

[params]
  author = "Liang Zhang"
  description = "Personal website and blog."
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  defaultTheme = "auto"
  
  [params.label]
    text = "Liang Zhang"
    icon = "images/zhengjianzhao.jpeg"
    iconHeight = 80

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/CV_zhangliang_AI.pdf"
    weight = 2
  
  [[menu.main]]
    identifier = "project"
    name = "Project"
    url = "/project/"
    weight = 3
  
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 4
